### ISSUE TITLE
Testcases: add tests to cover everything

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/rml-cc#33]
Would be nice to have test cases covering the complete specification:

- Validating SHACL shapes from #32 
- Implementations validating their code
- ...

**Comment by chrdebru** [comment]
@DylanVanAssche, I'm a bit lost: I have found two Google Spreadsheets documents with test cases (one containing FNO and another FNO, IO, and STAR). 

How should we validate the SHACL shapes and communicate those? Have a bunch of graphs with and without mistakes to test everything? If yes, is there a protocol to follow?

**Comment by DylanVanAssche** [comment]
> I'm a bit lost: I have found two Google Spreadsheets documents with test cases (one containing FNO and another FNO, IO, and STAR).

It seems that there are multiple spreadsheets going around, could you send me the link in private?

> How should we validate the SHACL shapes and communicate those? Have a bunch of graphs with and without mistakes to test everything? If yes, is there a protocol to follow?

In rml-io I have set up CI/CD which takes the SHACL shape and applies it on every test case. Currently, rml-io only has passing test-cases, without test-cases which verifies the violation of each possible combination. I would suggest to start with only the valid ones, violating test-cases is a lot more work than the non-violating ones (which is already a lot depending on how much properties and combinations you can have in the spec). One you have the non-violating ones, you can make derivates that violate cardinality, invalid use of Literal/IRI/blanknode, etc.

**Comment by chrdebru** [comment]
Must have:
- [ ] Unnamed lists, bags, sequences, and alternatives.
- [ ] Named lists, bags, sequences, and alternatives.
- [ ] Empty lists and containers
- [ ] Append strategy
- [ ] Cartesian product strategy
- [ ] Lists and containers as objects

Nice to have:
- [ ] Nested gather maps

@DylanVanAssche Any guidelines on testing blank nodes? Are you using graph isomorphosisms to check those in other modules?

**Comment by DylanVanAssche** [comment]
Graph isomorphosisms indeed for blanknodes.

**Comment by chrdebru** [comment]
The test cases have been created in the branch [rml-cc-test-cases](https://github.com/kg-construct/rml-cc/tree/rml-cc-test-cases). 

@DylanVanAssche It covers more than the suggested test cases. The spreadsheet contains details on each test.
@frmichel Could you have a look at the branch? A pull request can be created after your approval.

**Comment by frmichel** [comment]
Hi @chrdebru, thx a lot for writing those tests.

I made some changes, however if you look at the diff you'll see that most of them are just about reordering the triples so that it was easier to verify.

Apart from that here are the other changes:
- I added a README with the list of tests and the tested features.
- I added missing triples "rdf:type rdf:List".
- RMLTC-CC-0004-SM1\default.nq and RMLTC-CC-0004-SM2\default.nq were a probably wrong copy-and-paste, I rewrote them
- I had one doubt in RMLTC-CC-0003-EL, the empty list is written this way:
```
<http://example.com/e/b> <http://example.com/ns#with> rdf:nil .
```
Shouldn't it be this instead?
```
<http://example.com/e/b> <http://example.com/ns#with> _:n0.
_:n0 rdf:type rdf:List .
_:n0 rdf:first rdf:nil .
```

I edited the files manually so a second check would be required to spot possible mistakes.
Thx.
Franck.

**Comment by chrdebru** [comment]
Thanks Franck!

`<http://example.com/e/b> <http://example.com/ns#with> rdf:nil .` is correct

What you wrote is a cons-pair where the first points to the empty list, and there is no rest. The list is either the empty list (base case) or a cons-pair where the first points to a value (which can be a list, by the way, as you have modeled it in your example), and the rest must be a list.

`<http://example.com/e/b> <http://example.com/ns#with> _:n0.
_:n0 rdf:type rdf:List .
_:n0 rdf:first rdf:nil 
_:n0 rdf:rest (2 3) .`

would correspond with `(() 2 3)`

**Comment by chrdebru** [comment]
Test cases implemented.
