### ISSUE TITLE
Two ontology NS prefixes in the documentation

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-cc#35]
The following file `./ontology/documentation/sections/introduction-en.html` has two ontology NS prefixes. Shouldn't we use `rml:` for the second? I do not want to propose a change, as maybe @anaigmo used a WIDOCO config file.

**Comment by frmichel** [comment]
Hi @chrdebru, I'm not sure what problem you are referring to in https://github.com/kg-construct/rml-cc/blob/main/ontology/documentation/sections/introduction-en.html.
Can you clarify?

**Comment by anaigmo** [comment]
Maybe I fixed this some while ago (and forgot to close the issue)? I only see one NS prefix for the ontology

**Comment by frmichel** [comment]
Ok thx @anaigmo, I close it. @chrdebru feel free to reopen if we missed something.
